# Generated by Django 3.2.10 on 2022-03-01 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tk',
            field=models.CharField(default=uuid.UUID('236530f5-3fa2-4ee0-8fbc-052da9092129'), max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
