# Generated by Django 3.2.10 on 2022-03-01 23:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_tk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tk',
            field=models.CharField(default=uuid.UUID('5759d2c6-6460-4e3d-9c66-99c630f8a97e'), max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
